apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "cspconsole.fullname" . }}-report-collector
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.reportCollector.hpa.replicaCount }}
  strategy:
    type: {{ .Values.reportCollector.deployment.type }}
    {{- if eq .Values.reportCollector.deployment.type "RollingUpdate" }}
    rollingUpdate:
      maxSurge: {{ .Values.reportCollector.deployment.maxSurge }}
      maxUnavailable: {{ .Values.reportCollector.deployment.maxUnavailable }}
    {{- end }}
  selector:
    matchLabels:
      app: {{ template "cspconsole.fullname" . }}-report-collector
  template:
    metadata:
      labels:
        app: {{ template "cspconsole.fullname" . }}-report-collector
    spec:
      {{- if .Values.reportCollector.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.reportCollector.nodeSelector | nindent 8 }}
      {{- end }}
      priorityClassName: high-priority
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{ template "cspconsole.fullname" . }}-report-collector
              topologyKey: "kubernetes.io/hostname"
      terminationGracePeriodSeconds: {{ .Values.reportCollector.terminationGracePeriod }}
      {{- if and .Values.global.externalServices.rabbitmq.serviceIp .Values.global.externalServices.rabbitmq.hostname }}
      hostAliases:
      - ip: {{ .Values.global.externalServices.rabbitmq.serviceIp }}
        hostnames:
        - {{ .Values.global.externalServices.rabbitmq.hostname | quote }}
      {{- end }}
      {{- with .Values.reportCollector.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.reportCollector.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: report-collector
        image: {{ template "cspconsole.reportCollector.repository" . }}
        imagePullPolicy: {{ .Values.reportCollector.image.pullPolicy }}
        securityContext:
          runAsNonRoot: true
        ports:
          - containerPort: 8000
        env:
        - name: QUEUE_HOST
          valueFrom:
            secretKeyRef:
              name: {{ .Values.reportCollector.secretName }}
              key: queueHost
        - name: QUEUE_PORT
          valueFrom:
            secretKeyRef:
              name: {{ .Values.reportCollector.secretName }}
              key: queuePort
        - name: QUEUE_NAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.reportCollector.secretName }}
              key: queueName
        - name: EXCHANGE_NAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.reportCollector.secretName }}
              key: exchangeName
        - name: QUEUE_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.reportCollector.secretName }}
              key: queueUsername
        - name: QUEUE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.reportCollector.secretName }}
              key: queuePassword
        - name: QUEUE_CACERT_FILE
          value: "/var/www/cspconsole/certs/ca_certificate.pem"
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: {{ .Values.reportCollector.secretName }}
              key: dbHost
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: {{ .Values.reportCollector.secretName }}
              key: dbPort
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: {{ .Values.reportCollector.secretName }}
              key: dbName
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.reportCollector.secretName }}
              key: dbUsername
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.reportCollector.secretName }}
              key: dbPassword
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: {{ .Values.reportCollector.secretName }}
              key: redisHost
        - name: REDIS_PORT
          valueFrom:
            secretKeyRef:
              name: {{ .Values.reportCollector.secretName }}
              key: redisPort
        livenessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - /opt/scripts/ping.sh
          initialDelaySeconds: 5
          periodSeconds: 60
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - /opt/scripts/status.sh
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 2
        {{- if .Values.reportCollector.resources }}
        resources:
          {{- toYaml .Values.reportCollector.resources | nindent 10 }}
        {{- end }}
        volumeMounts:
        {{- if .Values.global.externalServices.rabbitmq.tls.enabled }}
        - name: queue-cacert
          mountPath: /var/www/cspconsole/certs/
          readOnly: true
        {{- end }}
      volumes:
      {{- if .Values.global.externalServices.rabbitmq.tls.enabled }}
      - name: queue-cacert
        secret:
          secretName: {{ default .Values.reportCollector.secretName .Values.global.externalServices.rabbitmq.tls.secretName }}
          items:
            - key: {{ .Values.global.externalServices.rabbitmq.tls.secretKey }}
              path: ca_certificate.pem
      {{- end }}
