apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "cspconsole.fullname" . }}-config-provider
  namespace: {{ required "Namespace not set" .Values.global.namespace }}
spec:
  minAvailable: {{ .Values.configProvider.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app: {{ template "cspconsole.fullname" . }}-config-provider