apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "cspconsole.fullname" . }}-config-provider
  namespace: {{ .Release.Namespace }}
spec:
  minAvailable: {{ .Values.configProvider.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app: {{ template "cspconsole.fullname" . }}-config-provider