{{- if .Values.global.deployment.enabled }}
kind: Service
apiVersion: v1
metadata:
  name: {{ template "cspconsole.fullname" . }}-config-provider
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ template "cspconsole.fullname" . }}-config-provider
  ports:
{{- range $index, $value := .Values.configProvider.service.ports }}
    - name: {{ $index }}
{{ toYaml $value | trim | indent 6 }}{{- end}}
{{- end }}
  type: {{ .Values.configProvider.service.type }}