apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "cspconsole.fullname" . }}-config-provider
  namespace: {{ required "Namespace not set" .Values.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "cspconsole.fullname" . }}-config-provider
  minReplicas: {{ .Values.configProvider.hpa.minReplicas }}
  maxReplicas: {{ .Values.configProvider.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.configProvider.hpa.averageUtilization }}