apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "cspconsole.fullname" . }}-config-provider
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.configProvider.hpa.replicaCount }}
  strategy:
    type: {{ .Values.configProvider.deployment.type }}
    {{- if eq .Values.configProvider.deployment.type "RollingUpdate" }}
    rollingUpdate:
      maxSurge: {{ .Values.configProvider.deployment.maxSurge }}
      maxUnavailable: {{ .Values.configProvider.deployment.maxUnavailable }}
    {{- end }}
  selector:
    matchLabels:
      app: {{ template "cspconsole.fullname" . }}-config-provider
  template:
    metadata:
      labels:
        app: {{ template "cspconsole.fullname" . }}-config-provider
    spec:
      {{- if .Values.configProvider.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.configProvider.nodeSelector | nindent 8 }}
      {{- end }}
      priorityClassName: high-priority
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{ template "cspconsole.fullname" . }}-config-provider
              topologyKey: "kubernetes.io/hostname"
      terminationGracePeriodSeconds: {{ .Values.configProvider.terminationGracePeriod }}
      {{- with .Values.configProvider.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.configProvider.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: config-provider
        image: {{ template "cspconsole.configProvider.repository" . }}
        imagePullPolicy: {{ .Values.configProvider.image.pullPolicy }}
        securityContext:
          runAsNonRoot: true
        ports:
          - containerPort: 8000
        env:
        - name: DB_HOST
          value: {{ .Values.global.externalServices.mysql.hostname | quote }}
        - name: DB_PORT
          value: {{ .Values.global.externalServices.mysql.port | quote }}
        - name: DB_DATABASE
          value: {{ .Values.global.externalServices.mysql.database | quote }}
        - name: DB_USERNAME
          value: {{ .Values.global.externalServices.mysql.username | quote }}
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.configProvider.secretName }}
              key: dbPassword
        - name: REDIS_HOST
          value: {{ .Values.global.externalServices.redis.hostname | quote }}
        - name: REDIS_PORT
          value: {{ .Values.global.externalServices.redis.port | quote }}
        livenessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - /opt/scripts/ping.sh
          initialDelaySeconds: 5
          periodSeconds: 60
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - /opt/scripts/status.sh
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 2
        {{- if .Values.configProvider.resources }}
        resources:
          {{- toYaml .Values.configProvider.resources | nindent 10 }}
        {{- end }}