{{- if .Values.global.ingress.enabled -}}
{{- $serviceName := include "cspconsole.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "cspconsole.fullname" . }}
  namespace: {{ required "Namespace not set" .Values.global.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/auth-tls-secret: {{ required "Namespace not set" .Values.global.namespace }}/{{ template "cspconsole.fullname" . }}-certs
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "10"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "10"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "10"
    nginx.ingress.kubernetes.io/limit-rpm: "1000"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "false"
    nginx.ingress.kubernetes.io/cors-allow-methods: GET, POST, OPTIONS
spec:
{{- if .Values.global.ingress.ingressClassName }}
  ingressClassName: {{ .Values.global.ingress.ingressClassName }}
{{- end }}
  tls:
  - hosts:
  {{- range .Values.global.ingress.tls.hosts }}
    - {{ . | quote }}
  {{- end }}
    secretName: {{ template "cspconsole.fullname" . }}-certs
  rules:
  {{- range .Values.global.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: /v1/(csp/)?reports?
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $serviceName }}-report-collector
                port:
                  number: 80
          - path: /v1/csp/(hash|header|directives)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $serviceName }}-config-provider
                port:
                  number: 80
  {{- end }}
{{- end -}}