apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "cspconsole.fullname" . }}-report-processor
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.reportProcessor.hpa.minReplicas }}
  strategy:
    type: {{ .Values.reportProcessor.deployment.type }}
    {{- if eq .Values.reportProcessor.deployment.type "RollingUpdate" }}
    rollingUpdate:
      maxSurge: {{ .Values.reportProcessor.deployment.maxSurge }}
      maxUnavailable: {{ .Values.reportProcessor.deployment.maxUnavailable }}
    {{- end }}
  selector:
    matchLabels:
      app: {{ template "cspconsole.fullname" . }}-report-processor
  template:
    metadata:
      labels:
        app: {{ template "cspconsole.fullname" . }}-report-processor
    spec:
      {{- if .Values.reportProcessor.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.reportProcessor.nodeSelector | nindent 8 }}
      {{- end }}
      priorityClassName: high-priority
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{ template "cspconsole.fullname" . }}-report-processor
              topologyKey: "kubernetes.io/hostname"
      terminationGracePeriodSeconds: {{ .Values.reportProcessor.terminationGracePeriod }}
      {{- if and .Values.global.externalServices.rabbitmq.serviceIp .Values.global.externalServices.rabbitmq.hostname }}
      hostAliases:
      - ip: {{ .Values.global.externalServices.rabbitmq.serviceIp }}
        hostnames:
        - {{ .Values.global.externalServices.rabbitmq.hostname | quote }}
      {{- end }}
      {{- with .Values.reportProcessor.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.reportProcessor.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: processor
        image: {{ template "cspconsole.reportProcessor.repository" . }}
        imagePullPolicy: {{ .Values.reportProcessor.image.pullPolicy }}
        args: ["node", "./build/Processor.js"]
        securityContext:
          runAsNonRoot: true
        env:
          - name: QUEUE_SCHEME
            value: {{ .Values.global.externalServices.rabbitmq.scheme | quote }}
          - name: QUEUE_HOST
            valueFrom:
              secretKeyRef:
                name: {{ .Values.reportProcessor.secretName }}
                key: queueHost
          - name: QUEUE_PORT
            value: {{ .Values.global.externalServices.rabbitmq.port | quote }}
          - name: QUEUE_NAME
            value: {{ .Values.global.externalServices.rabbitmq.queueName | quote }}
          - name: EXCHANGE_NAME
            value: {{ .Values.global.externalServices.rabbitmq.exchangeName | quote }}
          - name: QUEUE_USERNAME
            value: {{ .Values.global.externalServices.rabbitmq.username | quote }}
          - name: QUEUE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.reportProcessor.secretName }}
                key: queuePassword
          - name: SEARCH_SCHEME
            value: {{ .Values.global.externalServices.elasticsearch.scheme | quote }}
          - name: SEARCH_HOST
            valueFrom:
              secretKeyRef:
                name: {{ .Values.reportProcessor.secretName }}
                key: searchHost
          - name: SEARCH_PORT
            value: {{ .Values.global.externalServices.elasticsearch.port | quote }}
          - name: SEARCH_USERNAME
            value: {{ .Values.global.externalServices.elasticsearch.username | quote }}
          - name: SEARCH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.reportProcessor.secretName }}
                key: searchPassword
          - name: SEARCH_INDEX
            value: {{ .Values.global.externalServices.elasticsearch.index | quote }}
          - name: REDIS_HOST
            value: {{ .Values.global.externalServices.redis.hostname | quote }}
          - name: REDIS_PORT
            value: {{ .Values.global.externalServices.redis.port | quote }}
          - name: LOGGER_LEVEL
            value: {{ .Values.reportProcessor.logger.level | quote }}
          - name: DB_HOST
            value: {{ .Values.global.externalServices.mysql.hostname | quote }}
          - name: DB_PORT
            value: {{ .Values.global.externalServices.mysql.port | quote }}
          - name: DB_DATABASE
            value: {{ .Values.global.externalServices.mysql.database | quote }}
          - name: DB_USERNAME
            value: {{ .Values.global.externalServices.mysql.username | quote }}
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.reportProcessor.secretName }}
                key: dbPassword
          - name: QUEUE_PREFETCH_COUNT
            value: "5"
        {{- if .Values.reportProcessor.resources }}
        resources:
          {{- toYaml .Values.reportProcessor.resources | nindent 10 }}
        {{- end }}
        lifecycle:
          preStop:
            exec:
              command: [
                "sh", "-c",
                # Gracefully shutdown google-chrome
                # SIGQUIT is signal number 3 based on kill -L
                # 10s to wait to deregister pod from control plane so that no new traffic comes in during termination
                "sleep 10 && kill -s 3 1",
              ]
        volumeMounts:
        {{- if .Values.global.externalServices.elasticsearch.tls.enabled }}
        - name: elastic-ca
          mountPath: /opt/servant/request-analyzer/certs/elasticsearch
          readOnly: true
        {{- end }}
        {{- if .Values.global.externalServices.rabbitmq.tls.enabled }}
        - name: rabbitmq-ca
          mountPath: /opt/servant/request-analyzer/certs/rabbitmq
          readOnly: true
        {{- end }}
      volumes:
      {{- if .Values.global.externalServices.elasticsearch.tls.enabled }}
      - name: elastic-ca
        secret:
          secretName: {{ default (include "cspconsole.fullname" .) .Values.global.externalServices.elasticsearch.tls.secretName }}
          items:
          - key: {{ .Values.global.externalServices.elasticsearch.tls.secretKey }}
            path: ca_certificate.pem
            mode: 0444
      {{- end }}
      {{- if .Values.global.externalServices.rabbitmq.tls.enabled }}
      - name: rabbitmq-ca
        secret:
          secretName: {{ default (include "cspconsole.fullname" .) .Values.global.externalServices.rabbitmq.tls.secretName }}
          items:
          - key: {{ .Values.global.externalServices.rabbitmq.tls.secretKey }}
            path: ca_certificate.pem
            mode: 0444
      {{- end }}
      
